
function tellMeAJoke(){
var jokesDiv = document.querySelector(".jokes");
    var jokes = [
        "Why don't scientists trust atoms? Because they make up everything!",
        "I told my wife she was drawing her eyebrows too high. She looked surprised.",
        "Parallel lines have so much in common. It's a shame they'll never meet.",
        "Why don't skeletons fight each other? They don't have the guts.",
        "I used to play piano by ear, but now I use my hands and fingers.",
        "Why couldn't the bicycle stand up by itself? It was two-tired.",
        "I'm reading a book on anti-gravity. It's impossible to put down!",
        "What do you call fake spaghetti? An impasta.",
        "Why did the scarecrow win an award? Because he was outstanding in his field!",
        "I told my wife she should embrace her mistakes. She gave me a hug.",
        "I used to be a baker because I kneaded dough.",
        "Why don't oysters donate to charity? Because they are shellfish.",
        "I only know 25 letters of the alphabet. I don't know y.",
        "Why did the tomato turn red? Because it saw the salad dressing!",
        "What did the grape do when it got stepped on? Nothing but let out a little wine.",
        "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
        "I used to be a baker because I kneaded dough.",
        "Why did the math book look sad? Because it had too many problems.",
        "I only know how to do addition on a calculator. It's a calculated risk.",
        "What's a vampire's favorite fruit? A blood orange.",
        "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
        "Why don't scientists trust atoms? Because they make up everything!",
        "Parallel lines have so much in common. It's a shame they'll never meet.",
        "Why don't skeletons fight each other? They don't have the guts.",
        "I used to play piano by ear, but now I use my hands and fingers.",
        "Why couldn't the bicycle stand up by itself? It was two-tired.",
        "I'm reading a book on anti-gravity. It's impossible to put down!",
        "What do you call fake spaghetti? An impasta.",
        "Why did the scarecrow win an award? Because he was outstanding in his field!",
        "I told my wife she should embrace her mistakes. She gave me a hug.",
        "I used to be a baker because I kneaded dough.",
        "Why don't oysters donate to charity? Because they are shellfish.",
        "I only know 25 letters of the alphabet. I don't know y.",
        "Why did the tomato turn red? Because it saw the salad dressing!",
        "What did the grape do when it got stepped on? Nothing but let out a little wine.",
        "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
        "I used to be a baker because I kneaded dough.",
        "Why did the math book look sad? Because it had too many problems.",
        "I only know how to do addition on a calculator. It's a calculated risk.",
        "What's a vampire's favorite fruit? A blood orange.",
        "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
        "Why did the scarecrow become a successful politician? Because he was outstanding in his field.",
        "I used to be a baker because I kneaded dough.",
        "Why don't scientists trust atoms? Because they make up everything!",
        "Parallel lines have so much in common. It's a shame they'll never meet.",
        "Why don't skeletons fight each other? They don't have the guts.",
        "I used to play piano by ear, but now I use my hands and fingers.",
        "Why couldn't the bicycle stand up by itself? It was two-tired.",
        "I'm reading a book on anti-gravity. It's impossible to put down!",
        "What do you call fake spaghetti? An impasta.",
        "Why did the scarecrow win an award? Because he was outstanding in his field!",
        "I told my wife she should embrace her mistakes. She gave me a hug.",
        "I used to be a baker because I kneaded dough.",
        "Why don't oysters donate to charity? Because they are shellfish.",
        "I only know 25 letters of the alphabet. I don't know y.",
        "Why did the tomato turn red? Because it saw the salad dressing!",
        "What did the grape do when it got stepped on? Nothing but let out a little wine.",
        "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
        "I used to be a baker because I kneaded dough.",
        "Why did the math book look sad? Because it had too many problems.",
        "I only know how to do addition on a calculator. It's a calculated risk.",
        "What's a vampire's favorite fruit? A blood orange.",
        "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
        "Why did the scarecrow become a successful politician? Because he was outstanding in his field.",
        "Why don't skeletons fight each other? They don't have the guts.",
        "I used to play piano by ear, but now I use my hands and fingers.",
        "Why couldn't the bicycle stand up by itself? It was two-tired.",
        "I'm reading a book on anti-gravity. It's impossible to put down!",
        "What do you call fake spaghetti? An impasta.",
        "Why did the scarecrow win an award? Because he was outstanding in his field!",
        "I told my wife she should embrace her mistakes. She gave me a hug.",
        "I used to be a baker because I kneaded dough.",
        "Why don't oysters donate to charity? Because they are shellfish.",
        "I only know 25 letters of the alphabet. I don't know y.",
        "Why did the tomato turn red? Because it saw the salad dressing!",
        "What did the grape do when it got stepped on? Nothing but let out a little wine.",
        "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
        "I used to be a baker because I kneaded dough.",
        "Why did the math book look sad? Because it had too many problems.",
        "I only know how to do addition on a calculator. It's a calculated risk.",
        "What's a vampire's favorite fruit? A blood orange.",
        "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
        "Why did the scarecrow become a successful politician? Because he was outstanding in his field.",
      ];
    var index = Math.floor(Math.random()*jokes.length);
    var joke = jokes[index];
    jokesDiv.innerHTML = joke;  
}


